// Code generated by counterfeiter. DO NOT EDIT.
package usecasesfakes

import (
	sync "sync"

	osbapi "github.com/pivotal-cf/ism/osbapi"
	usecases "github.com/pivotal-cf/ism/usecases"
)

type FakeBindingFetcher struct {
	GetBindingByNameStub        func(string) (*osbapi.Binding, error)
	getBindingByNameMutex       sync.RWMutex
	getBindingByNameArgsForCall []struct {
		arg1 string
	}
	getBindingByNameReturns struct {
		result1 *osbapi.Binding
		result2 error
	}
	getBindingByNameReturnsOnCall map[int]struct {
		result1 *osbapi.Binding
		result2 error
	}
	GetBindingsStub        func() ([]*osbapi.Binding, error)
	getBindingsMutex       sync.RWMutex
	getBindingsArgsForCall []struct {
	}
	getBindingsReturns struct {
		result1 []*osbapi.Binding
		result2 error
	}
	getBindingsReturnsOnCall map[int]struct {
		result1 []*osbapi.Binding
		result2 error
	}
	GetBindingsForInstanceStub        func(string) ([]*osbapi.Binding, error)
	getBindingsForInstanceMutex       sync.RWMutex
	getBindingsForInstanceArgsForCall []struct {
		arg1 string
	}
	getBindingsForInstanceReturns struct {
		result1 []*osbapi.Binding
		result2 error
	}
	getBindingsForInstanceReturnsOnCall map[int]struct {
		result1 []*osbapi.Binding
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBindingFetcher) GetBindingByName(arg1 string) (*osbapi.Binding, error) {
	fake.getBindingByNameMutex.Lock()
	ret, specificReturn := fake.getBindingByNameReturnsOnCall[len(fake.getBindingByNameArgsForCall)]
	fake.getBindingByNameArgsForCall = append(fake.getBindingByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetBindingByName", []interface{}{arg1})
	fake.getBindingByNameMutex.Unlock()
	if fake.GetBindingByNameStub != nil {
		return fake.GetBindingByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBindingByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingFetcher) GetBindingByNameCallCount() int {
	fake.getBindingByNameMutex.RLock()
	defer fake.getBindingByNameMutex.RUnlock()
	return len(fake.getBindingByNameArgsForCall)
}

func (fake *FakeBindingFetcher) GetBindingByNameCalls(stub func(string) (*osbapi.Binding, error)) {
	fake.getBindingByNameMutex.Lock()
	defer fake.getBindingByNameMutex.Unlock()
	fake.GetBindingByNameStub = stub
}

func (fake *FakeBindingFetcher) GetBindingByNameArgsForCall(i int) string {
	fake.getBindingByNameMutex.RLock()
	defer fake.getBindingByNameMutex.RUnlock()
	argsForCall := fake.getBindingByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingFetcher) GetBindingByNameReturns(result1 *osbapi.Binding, result2 error) {
	fake.getBindingByNameMutex.Lock()
	defer fake.getBindingByNameMutex.Unlock()
	fake.GetBindingByNameStub = nil
	fake.getBindingByNameReturns = struct {
		result1 *osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingFetcher) GetBindingByNameReturnsOnCall(i int, result1 *osbapi.Binding, result2 error) {
	fake.getBindingByNameMutex.Lock()
	defer fake.getBindingByNameMutex.Unlock()
	fake.GetBindingByNameStub = nil
	if fake.getBindingByNameReturnsOnCall == nil {
		fake.getBindingByNameReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Binding
			result2 error
		})
	}
	fake.getBindingByNameReturnsOnCall[i] = struct {
		result1 *osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingFetcher) GetBindings() ([]*osbapi.Binding, error) {
	fake.getBindingsMutex.Lock()
	ret, specificReturn := fake.getBindingsReturnsOnCall[len(fake.getBindingsArgsForCall)]
	fake.getBindingsArgsForCall = append(fake.getBindingsArgsForCall, struct {
	}{})
	fake.recordInvocation("GetBindings", []interface{}{})
	fake.getBindingsMutex.Unlock()
	if fake.GetBindingsStub != nil {
		return fake.GetBindingsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBindingsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingFetcher) GetBindingsCallCount() int {
	fake.getBindingsMutex.RLock()
	defer fake.getBindingsMutex.RUnlock()
	return len(fake.getBindingsArgsForCall)
}

func (fake *FakeBindingFetcher) GetBindingsCalls(stub func() ([]*osbapi.Binding, error)) {
	fake.getBindingsMutex.Lock()
	defer fake.getBindingsMutex.Unlock()
	fake.GetBindingsStub = stub
}

func (fake *FakeBindingFetcher) GetBindingsReturns(result1 []*osbapi.Binding, result2 error) {
	fake.getBindingsMutex.Lock()
	defer fake.getBindingsMutex.Unlock()
	fake.GetBindingsStub = nil
	fake.getBindingsReturns = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingFetcher) GetBindingsReturnsOnCall(i int, result1 []*osbapi.Binding, result2 error) {
	fake.getBindingsMutex.Lock()
	defer fake.getBindingsMutex.Unlock()
	fake.GetBindingsStub = nil
	if fake.getBindingsReturnsOnCall == nil {
		fake.getBindingsReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Binding
			result2 error
		})
	}
	fake.getBindingsReturnsOnCall[i] = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingFetcher) GetBindingsForInstance(arg1 string) ([]*osbapi.Binding, error) {
	fake.getBindingsForInstanceMutex.Lock()
	ret, specificReturn := fake.getBindingsForInstanceReturnsOnCall[len(fake.getBindingsForInstanceArgsForCall)]
	fake.getBindingsForInstanceArgsForCall = append(fake.getBindingsForInstanceArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetBindingsForInstance", []interface{}{arg1})
	fake.getBindingsForInstanceMutex.Unlock()
	if fake.GetBindingsForInstanceStub != nil {
		return fake.GetBindingsForInstanceStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBindingsForInstanceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingFetcher) GetBindingsForInstanceCallCount() int {
	fake.getBindingsForInstanceMutex.RLock()
	defer fake.getBindingsForInstanceMutex.RUnlock()
	return len(fake.getBindingsForInstanceArgsForCall)
}

func (fake *FakeBindingFetcher) GetBindingsForInstanceCalls(stub func(string) ([]*osbapi.Binding, error)) {
	fake.getBindingsForInstanceMutex.Lock()
	defer fake.getBindingsForInstanceMutex.Unlock()
	fake.GetBindingsForInstanceStub = stub
}

func (fake *FakeBindingFetcher) GetBindingsForInstanceArgsForCall(i int) string {
	fake.getBindingsForInstanceMutex.RLock()
	defer fake.getBindingsForInstanceMutex.RUnlock()
	argsForCall := fake.getBindingsForInstanceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingFetcher) GetBindingsForInstanceReturns(result1 []*osbapi.Binding, result2 error) {
	fake.getBindingsForInstanceMutex.Lock()
	defer fake.getBindingsForInstanceMutex.Unlock()
	fake.GetBindingsForInstanceStub = nil
	fake.getBindingsForInstanceReturns = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingFetcher) GetBindingsForInstanceReturnsOnCall(i int, result1 []*osbapi.Binding, result2 error) {
	fake.getBindingsForInstanceMutex.Lock()
	defer fake.getBindingsForInstanceMutex.Unlock()
	fake.GetBindingsForInstanceStub = nil
	if fake.getBindingsForInstanceReturnsOnCall == nil {
		fake.getBindingsForInstanceReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Binding
			result2 error
		})
	}
	fake.getBindingsForInstanceReturnsOnCall[i] = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getBindingByNameMutex.RLock()
	defer fake.getBindingByNameMutex.RUnlock()
	fake.getBindingsMutex.RLock()
	defer fake.getBindingsMutex.RUnlock()
	fake.getBindingsForInstanceMutex.RLock()
	defer fake.getBindingsForInstanceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBindingFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecases.BindingFetcher = new(FakeBindingFetcher)
