// Code generated by counterfeiter. DO NOT EDIT.
package usecasesfakes

import (
	"sync"

	"github.com/pivotal-cf/ism/osbapi"
	"github.com/pivotal-cf/ism/usecases"
)

type FakeBrokerFetcher struct {
	GetBrokerByNameStub        func(string) (*osbapi.Broker, error)
	getBrokerByNameMutex       sync.RWMutex
	getBrokerByNameArgsForCall []struct {
		arg1 string
	}
	getBrokerByNameReturns struct {
		result1 *osbapi.Broker
		result2 error
	}
	getBrokerByNameReturnsOnCall map[int]struct {
		result1 *osbapi.Broker
		result2 error
	}
	GetBrokersStub        func() ([]*osbapi.Broker, error)
	getBrokersMutex       sync.RWMutex
	getBrokersArgsForCall []struct {
	}
	getBrokersReturns struct {
		result1 []*osbapi.Broker
		result2 error
	}
	getBrokersReturnsOnCall map[int]struct {
		result1 []*osbapi.Broker
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBrokerFetcher) GetBrokerByName(arg1 string) (*osbapi.Broker, error) {
	fake.getBrokerByNameMutex.Lock()
	ret, specificReturn := fake.getBrokerByNameReturnsOnCall[len(fake.getBrokerByNameArgsForCall)]
	fake.getBrokerByNameArgsForCall = append(fake.getBrokerByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetBrokerByName", []interface{}{arg1})
	fake.getBrokerByNameMutex.Unlock()
	if fake.GetBrokerByNameStub != nil {
		return fake.GetBrokerByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBrokerByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBrokerFetcher) GetBrokerByNameCallCount() int {
	fake.getBrokerByNameMutex.RLock()
	defer fake.getBrokerByNameMutex.RUnlock()
	return len(fake.getBrokerByNameArgsForCall)
}

func (fake *FakeBrokerFetcher) GetBrokerByNameCalls(stub func(string) (*osbapi.Broker, error)) {
	fake.getBrokerByNameMutex.Lock()
	defer fake.getBrokerByNameMutex.Unlock()
	fake.GetBrokerByNameStub = stub
}

func (fake *FakeBrokerFetcher) GetBrokerByNameArgsForCall(i int) string {
	fake.getBrokerByNameMutex.RLock()
	defer fake.getBrokerByNameMutex.RUnlock()
	argsForCall := fake.getBrokerByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBrokerFetcher) GetBrokerByNameReturns(result1 *osbapi.Broker, result2 error) {
	fake.getBrokerByNameMutex.Lock()
	defer fake.getBrokerByNameMutex.Unlock()
	fake.GetBrokerByNameStub = nil
	fake.getBrokerByNameReturns = struct {
		result1 *osbapi.Broker
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerFetcher) GetBrokerByNameReturnsOnCall(i int, result1 *osbapi.Broker, result2 error) {
	fake.getBrokerByNameMutex.Lock()
	defer fake.getBrokerByNameMutex.Unlock()
	fake.GetBrokerByNameStub = nil
	if fake.getBrokerByNameReturnsOnCall == nil {
		fake.getBrokerByNameReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Broker
			result2 error
		})
	}
	fake.getBrokerByNameReturnsOnCall[i] = struct {
		result1 *osbapi.Broker
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerFetcher) GetBrokers() ([]*osbapi.Broker, error) {
	fake.getBrokersMutex.Lock()
	ret, specificReturn := fake.getBrokersReturnsOnCall[len(fake.getBrokersArgsForCall)]
	fake.getBrokersArgsForCall = append(fake.getBrokersArgsForCall, struct {
	}{})
	fake.recordInvocation("GetBrokers", []interface{}{})
	fake.getBrokersMutex.Unlock()
	if fake.GetBrokersStub != nil {
		return fake.GetBrokersStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBrokersReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBrokerFetcher) GetBrokersCallCount() int {
	fake.getBrokersMutex.RLock()
	defer fake.getBrokersMutex.RUnlock()
	return len(fake.getBrokersArgsForCall)
}

func (fake *FakeBrokerFetcher) GetBrokersCalls(stub func() ([]*osbapi.Broker, error)) {
	fake.getBrokersMutex.Lock()
	defer fake.getBrokersMutex.Unlock()
	fake.GetBrokersStub = stub
}

func (fake *FakeBrokerFetcher) GetBrokersReturns(result1 []*osbapi.Broker, result2 error) {
	fake.getBrokersMutex.Lock()
	defer fake.getBrokersMutex.Unlock()
	fake.GetBrokersStub = nil
	fake.getBrokersReturns = struct {
		result1 []*osbapi.Broker
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerFetcher) GetBrokersReturnsOnCall(i int, result1 []*osbapi.Broker, result2 error) {
	fake.getBrokersMutex.Lock()
	defer fake.getBrokersMutex.Unlock()
	fake.GetBrokersStub = nil
	if fake.getBrokersReturnsOnCall == nil {
		fake.getBrokersReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Broker
			result2 error
		})
	}
	fake.getBrokersReturnsOnCall[i] = struct {
		result1 []*osbapi.Broker
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getBrokerByNameMutex.RLock()
	defer fake.getBrokerByNameMutex.RUnlock()
	fake.getBrokersMutex.RLock()
	defer fake.getBrokersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBrokerFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecases.BrokerFetcher = new(FakeBrokerFetcher)
