// Code generated by counterfeiter. DO NOT EDIT.
package usecasesfakes

import (
	sync "sync"

	osbapi "github.com/pivotal-cf/ism/osbapi"
	usecases "github.com/pivotal-cf/ism/usecases"
)

type FakeInstanceFetcher struct {
	GetInstanceByIDStub        func(string) (*osbapi.Instance, error)
	getInstanceByIDMutex       sync.RWMutex
	getInstanceByIDArgsForCall []struct {
		arg1 string
	}
	getInstanceByIDReturns struct {
		result1 *osbapi.Instance
		result2 error
	}
	getInstanceByIDReturnsOnCall map[int]struct {
		result1 *osbapi.Instance
		result2 error
	}
	GetInstanceByNameStub        func(string) (*osbapi.Instance, error)
	getInstanceByNameMutex       sync.RWMutex
	getInstanceByNameArgsForCall []struct {
		arg1 string
	}
	getInstanceByNameReturns struct {
		result1 *osbapi.Instance
		result2 error
	}
	getInstanceByNameReturnsOnCall map[int]struct {
		result1 *osbapi.Instance
		result2 error
	}
	GetInstancesStub        func() ([]*osbapi.Instance, error)
	getInstancesMutex       sync.RWMutex
	getInstancesArgsForCall []struct {
	}
	getInstancesReturns struct {
		result1 []*osbapi.Instance
		result2 error
	}
	getInstancesReturnsOnCall map[int]struct {
		result1 []*osbapi.Instance
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInstanceFetcher) GetInstanceByID(arg1 string) (*osbapi.Instance, error) {
	fake.getInstanceByIDMutex.Lock()
	ret, specificReturn := fake.getInstanceByIDReturnsOnCall[len(fake.getInstanceByIDArgsForCall)]
	fake.getInstanceByIDArgsForCall = append(fake.getInstanceByIDArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetInstanceByID", []interface{}{arg1})
	fake.getInstanceByIDMutex.Unlock()
	if fake.GetInstanceByIDStub != nil {
		return fake.GetInstanceByIDStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getInstanceByIDReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceFetcher) GetInstanceByIDCallCount() int {
	fake.getInstanceByIDMutex.RLock()
	defer fake.getInstanceByIDMutex.RUnlock()
	return len(fake.getInstanceByIDArgsForCall)
}

func (fake *FakeInstanceFetcher) GetInstanceByIDCalls(stub func(string) (*osbapi.Instance, error)) {
	fake.getInstanceByIDMutex.Lock()
	defer fake.getInstanceByIDMutex.Unlock()
	fake.GetInstanceByIDStub = stub
}

func (fake *FakeInstanceFetcher) GetInstanceByIDArgsForCall(i int) string {
	fake.getInstanceByIDMutex.RLock()
	defer fake.getInstanceByIDMutex.RUnlock()
	argsForCall := fake.getInstanceByIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceFetcher) GetInstanceByIDReturns(result1 *osbapi.Instance, result2 error) {
	fake.getInstanceByIDMutex.Lock()
	defer fake.getInstanceByIDMutex.Unlock()
	fake.GetInstanceByIDStub = nil
	fake.getInstanceByIDReturns = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceFetcher) GetInstanceByIDReturnsOnCall(i int, result1 *osbapi.Instance, result2 error) {
	fake.getInstanceByIDMutex.Lock()
	defer fake.getInstanceByIDMutex.Unlock()
	fake.GetInstanceByIDStub = nil
	if fake.getInstanceByIDReturnsOnCall == nil {
		fake.getInstanceByIDReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Instance
			result2 error
		})
	}
	fake.getInstanceByIDReturnsOnCall[i] = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceFetcher) GetInstanceByName(arg1 string) (*osbapi.Instance, error) {
	fake.getInstanceByNameMutex.Lock()
	ret, specificReturn := fake.getInstanceByNameReturnsOnCall[len(fake.getInstanceByNameArgsForCall)]
	fake.getInstanceByNameArgsForCall = append(fake.getInstanceByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetInstanceByName", []interface{}{arg1})
	fake.getInstanceByNameMutex.Unlock()
	if fake.GetInstanceByNameStub != nil {
		return fake.GetInstanceByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getInstanceByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceFetcher) GetInstanceByNameCallCount() int {
	fake.getInstanceByNameMutex.RLock()
	defer fake.getInstanceByNameMutex.RUnlock()
	return len(fake.getInstanceByNameArgsForCall)
}

func (fake *FakeInstanceFetcher) GetInstanceByNameCalls(stub func(string) (*osbapi.Instance, error)) {
	fake.getInstanceByNameMutex.Lock()
	defer fake.getInstanceByNameMutex.Unlock()
	fake.GetInstanceByNameStub = stub
}

func (fake *FakeInstanceFetcher) GetInstanceByNameArgsForCall(i int) string {
	fake.getInstanceByNameMutex.RLock()
	defer fake.getInstanceByNameMutex.RUnlock()
	argsForCall := fake.getInstanceByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceFetcher) GetInstanceByNameReturns(result1 *osbapi.Instance, result2 error) {
	fake.getInstanceByNameMutex.Lock()
	defer fake.getInstanceByNameMutex.Unlock()
	fake.GetInstanceByNameStub = nil
	fake.getInstanceByNameReturns = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceFetcher) GetInstanceByNameReturnsOnCall(i int, result1 *osbapi.Instance, result2 error) {
	fake.getInstanceByNameMutex.Lock()
	defer fake.getInstanceByNameMutex.Unlock()
	fake.GetInstanceByNameStub = nil
	if fake.getInstanceByNameReturnsOnCall == nil {
		fake.getInstanceByNameReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Instance
			result2 error
		})
	}
	fake.getInstanceByNameReturnsOnCall[i] = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceFetcher) GetInstances() ([]*osbapi.Instance, error) {
	fake.getInstancesMutex.Lock()
	ret, specificReturn := fake.getInstancesReturnsOnCall[len(fake.getInstancesArgsForCall)]
	fake.getInstancesArgsForCall = append(fake.getInstancesArgsForCall, struct {
	}{})
	fake.recordInvocation("GetInstances", []interface{}{})
	fake.getInstancesMutex.Unlock()
	if fake.GetInstancesStub != nil {
		return fake.GetInstancesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getInstancesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceFetcher) GetInstancesCallCount() int {
	fake.getInstancesMutex.RLock()
	defer fake.getInstancesMutex.RUnlock()
	return len(fake.getInstancesArgsForCall)
}

func (fake *FakeInstanceFetcher) GetInstancesCalls(stub func() ([]*osbapi.Instance, error)) {
	fake.getInstancesMutex.Lock()
	defer fake.getInstancesMutex.Unlock()
	fake.GetInstancesStub = stub
}

func (fake *FakeInstanceFetcher) GetInstancesReturns(result1 []*osbapi.Instance, result2 error) {
	fake.getInstancesMutex.Lock()
	defer fake.getInstancesMutex.Unlock()
	fake.GetInstancesStub = nil
	fake.getInstancesReturns = struct {
		result1 []*osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceFetcher) GetInstancesReturnsOnCall(i int, result1 []*osbapi.Instance, result2 error) {
	fake.getInstancesMutex.Lock()
	defer fake.getInstancesMutex.Unlock()
	fake.GetInstancesStub = nil
	if fake.getInstancesReturnsOnCall == nil {
		fake.getInstancesReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Instance
			result2 error
		})
	}
	fake.getInstancesReturnsOnCall[i] = struct {
		result1 []*osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getInstanceByIDMutex.RLock()
	defer fake.getInstanceByIDMutex.RUnlock()
	fake.getInstanceByNameMutex.RLock()
	defer fake.getInstanceByNameMutex.RUnlock()
	fake.getInstancesMutex.RLock()
	defer fake.getInstancesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInstanceFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecases.InstanceFetcher = new(FakeInstanceFetcher)
