apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - osbapi.ism.io
  resources:
  - brokers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - osbapi.ism.io
  resources:
  - brokers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - osbapi.ism.io
  resources:
  - brokerservices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - osbapi.ism.io
  resources:
  - brokerservices/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - osbapi.ism.io
  resources:
  - brokerserviceplans
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - osbapi.ism.io
  resources:
  - brokerserviceplans/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - osbapi.ism.io
  resources:
  - serviceinstances
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - osbapi.ism.io
  resources:
  - serviceinstances/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
