// Code generated by counterfeiter. DO NOT EDIT.
package actorsfakes

import (
	sync "sync"

	actors "github.com/pivotal-cf/ism/actors"
	osbapi "github.com/pivotal-cf/ism/osbapi"
)

type FakeInstanceRepository struct {
	CreateStub        func(*osbapi.Instance) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *osbapi.Instance
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	FindAllStub        func() ([]*osbapi.Instance, error)
	findAllMutex       sync.RWMutex
	findAllArgsForCall []struct {
	}
	findAllReturns struct {
		result1 []*osbapi.Instance
		result2 error
	}
	findAllReturnsOnCall map[int]struct {
		result1 []*osbapi.Instance
		result2 error
	}
	FindAllForBrokerStub        func(string) ([]*osbapi.Instance, error)
	findAllForBrokerMutex       sync.RWMutex
	findAllForBrokerArgsForCall []struct {
		arg1 string
	}
	findAllForBrokerReturns struct {
		result1 []*osbapi.Instance
		result2 error
	}
	findAllForBrokerReturnsOnCall map[int]struct {
		result1 []*osbapi.Instance
		result2 error
	}
	FindByIDStub        func(string) (*osbapi.Instance, error)
	findByIDMutex       sync.RWMutex
	findByIDArgsForCall []struct {
		arg1 string
	}
	findByIDReturns struct {
		result1 *osbapi.Instance
		result2 error
	}
	findByIDReturnsOnCall map[int]struct {
		result1 *osbapi.Instance
		result2 error
	}
	FindByNameStub        func(string) (*osbapi.Instance, error)
	findByNameMutex       sync.RWMutex
	findByNameArgsForCall []struct {
		arg1 string
	}
	findByNameReturns struct {
		result1 *osbapi.Instance
		result2 error
	}
	findByNameReturnsOnCall map[int]struct {
		result1 *osbapi.Instance
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInstanceRepository) Create(arg1 *osbapi.Instance) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *osbapi.Instance
	}{arg1})
	fake.recordInvocation("Create", []interface{}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createReturns
	return fakeReturns.result1
}

func (fake *FakeInstanceRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeInstanceRepository) CreateCalls(stub func(*osbapi.Instance) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeInstanceRepository) CreateArgsForCall(i int) *osbapi.Instance {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeInstanceRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeInstanceRepository) Delete(arg1 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteReturns
	return fakeReturns.result1
}

func (fake *FakeInstanceRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeInstanceRepository) DeleteCalls(stub func(string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeInstanceRepository) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeInstanceRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeInstanceRepository) FindAll() ([]*osbapi.Instance, error) {
	fake.findAllMutex.Lock()
	ret, specificReturn := fake.findAllReturnsOnCall[len(fake.findAllArgsForCall)]
	fake.findAllArgsForCall = append(fake.findAllArgsForCall, struct {
	}{})
	fake.recordInvocation("FindAll", []interface{}{})
	fake.findAllMutex.Unlock()
	if fake.FindAllStub != nil {
		return fake.FindAllStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findAllReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceRepository) FindAllCallCount() int {
	fake.findAllMutex.RLock()
	defer fake.findAllMutex.RUnlock()
	return len(fake.findAllArgsForCall)
}

func (fake *FakeInstanceRepository) FindAllCalls(stub func() ([]*osbapi.Instance, error)) {
	fake.findAllMutex.Lock()
	defer fake.findAllMutex.Unlock()
	fake.FindAllStub = stub
}

func (fake *FakeInstanceRepository) FindAllReturns(result1 []*osbapi.Instance, result2 error) {
	fake.findAllMutex.Lock()
	defer fake.findAllMutex.Unlock()
	fake.FindAllStub = nil
	fake.findAllReturns = struct {
		result1 []*osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindAllReturnsOnCall(i int, result1 []*osbapi.Instance, result2 error) {
	fake.findAllMutex.Lock()
	defer fake.findAllMutex.Unlock()
	fake.FindAllStub = nil
	if fake.findAllReturnsOnCall == nil {
		fake.findAllReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Instance
			result2 error
		})
	}
	fake.findAllReturnsOnCall[i] = struct {
		result1 []*osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindAllForBroker(arg1 string) ([]*osbapi.Instance, error) {
	fake.findAllForBrokerMutex.Lock()
	ret, specificReturn := fake.findAllForBrokerReturnsOnCall[len(fake.findAllForBrokerArgsForCall)]
	fake.findAllForBrokerArgsForCall = append(fake.findAllForBrokerArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("FindAllForBroker", []interface{}{arg1})
	fake.findAllForBrokerMutex.Unlock()
	if fake.FindAllForBrokerStub != nil {
		return fake.FindAllForBrokerStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findAllForBrokerReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceRepository) FindAllForBrokerCallCount() int {
	fake.findAllForBrokerMutex.RLock()
	defer fake.findAllForBrokerMutex.RUnlock()
	return len(fake.findAllForBrokerArgsForCall)
}

func (fake *FakeInstanceRepository) FindAllForBrokerCalls(stub func(string) ([]*osbapi.Instance, error)) {
	fake.findAllForBrokerMutex.Lock()
	defer fake.findAllForBrokerMutex.Unlock()
	fake.FindAllForBrokerStub = stub
}

func (fake *FakeInstanceRepository) FindAllForBrokerArgsForCall(i int) string {
	fake.findAllForBrokerMutex.RLock()
	defer fake.findAllForBrokerMutex.RUnlock()
	argsForCall := fake.findAllForBrokerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceRepository) FindAllForBrokerReturns(result1 []*osbapi.Instance, result2 error) {
	fake.findAllForBrokerMutex.Lock()
	defer fake.findAllForBrokerMutex.Unlock()
	fake.FindAllForBrokerStub = nil
	fake.findAllForBrokerReturns = struct {
		result1 []*osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindAllForBrokerReturnsOnCall(i int, result1 []*osbapi.Instance, result2 error) {
	fake.findAllForBrokerMutex.Lock()
	defer fake.findAllForBrokerMutex.Unlock()
	fake.FindAllForBrokerStub = nil
	if fake.findAllForBrokerReturnsOnCall == nil {
		fake.findAllForBrokerReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Instance
			result2 error
		})
	}
	fake.findAllForBrokerReturnsOnCall[i] = struct {
		result1 []*osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindByID(arg1 string) (*osbapi.Instance, error) {
	fake.findByIDMutex.Lock()
	ret, specificReturn := fake.findByIDReturnsOnCall[len(fake.findByIDArgsForCall)]
	fake.findByIDArgsForCall = append(fake.findByIDArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("FindByID", []interface{}{arg1})
	fake.findByIDMutex.Unlock()
	if fake.FindByIDStub != nil {
		return fake.FindByIDStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findByIDReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceRepository) FindByIDCallCount() int {
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	return len(fake.findByIDArgsForCall)
}

func (fake *FakeInstanceRepository) FindByIDCalls(stub func(string) (*osbapi.Instance, error)) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = stub
}

func (fake *FakeInstanceRepository) FindByIDArgsForCall(i int) string {
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	argsForCall := fake.findByIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceRepository) FindByIDReturns(result1 *osbapi.Instance, result2 error) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = nil
	fake.findByIDReturns = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindByIDReturnsOnCall(i int, result1 *osbapi.Instance, result2 error) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = nil
	if fake.findByIDReturnsOnCall == nil {
		fake.findByIDReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Instance
			result2 error
		})
	}
	fake.findByIDReturnsOnCall[i] = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindByName(arg1 string) (*osbapi.Instance, error) {
	fake.findByNameMutex.Lock()
	ret, specificReturn := fake.findByNameReturnsOnCall[len(fake.findByNameArgsForCall)]
	fake.findByNameArgsForCall = append(fake.findByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("FindByName", []interface{}{arg1})
	fake.findByNameMutex.Unlock()
	if fake.FindByNameStub != nil {
		return fake.FindByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceRepository) FindByNameCallCount() int {
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	return len(fake.findByNameArgsForCall)
}

func (fake *FakeInstanceRepository) FindByNameCalls(stub func(string) (*osbapi.Instance, error)) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = stub
}

func (fake *FakeInstanceRepository) FindByNameArgsForCall(i int) string {
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	argsForCall := fake.findByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeInstanceRepository) FindByNameReturns(result1 *osbapi.Instance, result2 error) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = nil
	fake.findByNameReturns = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) FindByNameReturnsOnCall(i int, result1 *osbapi.Instance, result2 error) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = nil
	if fake.findByNameReturnsOnCall == nil {
		fake.findByNameReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Instance
			result2 error
		})
	}
	fake.findByNameReturnsOnCall[i] = struct {
		result1 *osbapi.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.findAllMutex.RLock()
	defer fake.findAllMutex.RUnlock()
	fake.findAllForBrokerMutex.RLock()
	defer fake.findAllForBrokerMutex.RUnlock()
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInstanceRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ actors.InstanceRepository = new(FakeInstanceRepository)
