// Code generated by counterfeiter. DO NOT EDIT.
package actorsfakes

import (
	sync "sync"

	actors "github.com/pivotal-cf/ism/actors"
	osbapi "github.com/pivotal-cf/ism/osbapi"
)

type FakeBindingRepository struct {
	CreateStub        func(*osbapi.Binding) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *osbapi.Binding
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	FindAllStub        func() ([]*osbapi.Binding, error)
	findAllMutex       sync.RWMutex
	findAllArgsForCall []struct {
	}
	findAllReturns struct {
		result1 []*osbapi.Binding
		result2 error
	}
	findAllReturnsOnCall map[int]struct {
		result1 []*osbapi.Binding
		result2 error
	}
	FindAllForInstanceStub        func(string) ([]*osbapi.Binding, error)
	findAllForInstanceMutex       sync.RWMutex
	findAllForInstanceArgsForCall []struct {
		arg1 string
	}
	findAllForInstanceReturns struct {
		result1 []*osbapi.Binding
		result2 error
	}
	findAllForInstanceReturnsOnCall map[int]struct {
		result1 []*osbapi.Binding
		result2 error
	}
	FindByNameStub        func(string) (*osbapi.Binding, error)
	findByNameMutex       sync.RWMutex
	findByNameArgsForCall []struct {
		arg1 string
	}
	findByNameReturns struct {
		result1 *osbapi.Binding
		result2 error
	}
	findByNameReturnsOnCall map[int]struct {
		result1 *osbapi.Binding
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBindingRepository) Create(arg1 *osbapi.Binding) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *osbapi.Binding
	}{arg1})
	fake.recordInvocation("Create", []interface{}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createReturns
	return fakeReturns.result1
}

func (fake *FakeBindingRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBindingRepository) CreateCalls(stub func(*osbapi.Binding) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeBindingRepository) CreateArgsForCall(i int) *osbapi.Binding {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBindingRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBindingRepository) Delete(arg1 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteReturns
	return fakeReturns.result1
}

func (fake *FakeBindingRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeBindingRepository) DeleteCalls(stub func(string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeBindingRepository) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBindingRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBindingRepository) FindAll() ([]*osbapi.Binding, error) {
	fake.findAllMutex.Lock()
	ret, specificReturn := fake.findAllReturnsOnCall[len(fake.findAllArgsForCall)]
	fake.findAllArgsForCall = append(fake.findAllArgsForCall, struct {
	}{})
	fake.recordInvocation("FindAll", []interface{}{})
	fake.findAllMutex.Unlock()
	if fake.FindAllStub != nil {
		return fake.FindAllStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findAllReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingRepository) FindAllCallCount() int {
	fake.findAllMutex.RLock()
	defer fake.findAllMutex.RUnlock()
	return len(fake.findAllArgsForCall)
}

func (fake *FakeBindingRepository) FindAllCalls(stub func() ([]*osbapi.Binding, error)) {
	fake.findAllMutex.Lock()
	defer fake.findAllMutex.Unlock()
	fake.FindAllStub = stub
}

func (fake *FakeBindingRepository) FindAllReturns(result1 []*osbapi.Binding, result2 error) {
	fake.findAllMutex.Lock()
	defer fake.findAllMutex.Unlock()
	fake.FindAllStub = nil
	fake.findAllReturns = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingRepository) FindAllReturnsOnCall(i int, result1 []*osbapi.Binding, result2 error) {
	fake.findAllMutex.Lock()
	defer fake.findAllMutex.Unlock()
	fake.FindAllStub = nil
	if fake.findAllReturnsOnCall == nil {
		fake.findAllReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Binding
			result2 error
		})
	}
	fake.findAllReturnsOnCall[i] = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingRepository) FindAllForInstance(arg1 string) ([]*osbapi.Binding, error) {
	fake.findAllForInstanceMutex.Lock()
	ret, specificReturn := fake.findAllForInstanceReturnsOnCall[len(fake.findAllForInstanceArgsForCall)]
	fake.findAllForInstanceArgsForCall = append(fake.findAllForInstanceArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("FindAllForInstance", []interface{}{arg1})
	fake.findAllForInstanceMutex.Unlock()
	if fake.FindAllForInstanceStub != nil {
		return fake.FindAllForInstanceStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findAllForInstanceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingRepository) FindAllForInstanceCallCount() int {
	fake.findAllForInstanceMutex.RLock()
	defer fake.findAllForInstanceMutex.RUnlock()
	return len(fake.findAllForInstanceArgsForCall)
}

func (fake *FakeBindingRepository) FindAllForInstanceCalls(stub func(string) ([]*osbapi.Binding, error)) {
	fake.findAllForInstanceMutex.Lock()
	defer fake.findAllForInstanceMutex.Unlock()
	fake.FindAllForInstanceStub = stub
}

func (fake *FakeBindingRepository) FindAllForInstanceArgsForCall(i int) string {
	fake.findAllForInstanceMutex.RLock()
	defer fake.findAllForInstanceMutex.RUnlock()
	argsForCall := fake.findAllForInstanceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingRepository) FindAllForInstanceReturns(result1 []*osbapi.Binding, result2 error) {
	fake.findAllForInstanceMutex.Lock()
	defer fake.findAllForInstanceMutex.Unlock()
	fake.FindAllForInstanceStub = nil
	fake.findAllForInstanceReturns = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingRepository) FindAllForInstanceReturnsOnCall(i int, result1 []*osbapi.Binding, result2 error) {
	fake.findAllForInstanceMutex.Lock()
	defer fake.findAllForInstanceMutex.Unlock()
	fake.FindAllForInstanceStub = nil
	if fake.findAllForInstanceReturnsOnCall == nil {
		fake.findAllForInstanceReturnsOnCall = make(map[int]struct {
			result1 []*osbapi.Binding
			result2 error
		})
	}
	fake.findAllForInstanceReturnsOnCall[i] = struct {
		result1 []*osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingRepository) FindByName(arg1 string) (*osbapi.Binding, error) {
	fake.findByNameMutex.Lock()
	ret, specificReturn := fake.findByNameReturnsOnCall[len(fake.findByNameArgsForCall)]
	fake.findByNameArgsForCall = append(fake.findByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("FindByName", []interface{}{arg1})
	fake.findByNameMutex.Unlock()
	if fake.FindByNameStub != nil {
		return fake.FindByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingRepository) FindByNameCallCount() int {
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	return len(fake.findByNameArgsForCall)
}

func (fake *FakeBindingRepository) FindByNameCalls(stub func(string) (*osbapi.Binding, error)) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = stub
}

func (fake *FakeBindingRepository) FindByNameArgsForCall(i int) string {
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	argsForCall := fake.findByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingRepository) FindByNameReturns(result1 *osbapi.Binding, result2 error) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = nil
	fake.findByNameReturns = struct {
		result1 *osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingRepository) FindByNameReturnsOnCall(i int, result1 *osbapi.Binding, result2 error) {
	fake.findByNameMutex.Lock()
	defer fake.findByNameMutex.Unlock()
	fake.FindByNameStub = nil
	if fake.findByNameReturnsOnCall == nil {
		fake.findByNameReturnsOnCall = make(map[int]struct {
			result1 *osbapi.Binding
			result2 error
		})
	}
	fake.findByNameReturnsOnCall[i] = struct {
		result1 *osbapi.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.findAllMutex.RLock()
	defer fake.findAllMutex.RUnlock()
	fake.findAllForInstanceMutex.RLock()
	defer fake.findAllForInstanceMutex.RUnlock()
	fake.findByNameMutex.RLock()
	defer fake.findByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBindingRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ actors.BindingRepository = new(FakeBindingRepository)
