// Code generated by counterfeiter. DO NOT EDIT.
package commandsfakes

import (
	"sync"

	"github.com/pivotal-cf/ism/commands"
)

type FakeUI struct {
	DisplayTableStub        func([][]string)
	displayTableMutex       sync.RWMutex
	displayTableArgsForCall []struct {
		arg1 [][]string
	}
	DisplayTextStub        func(string, ...map[string]interface{})
	displayTextMutex       sync.RWMutex
	displayTextArgsForCall []struct {
		arg1 string
		arg2 []map[string]interface{}
	}
	DisplayYAMLStub        func(interface{}) error
	displayYAMLMutex       sync.RWMutex
	displayYAMLArgsForCall []struct {
		arg1 interface{}
	}
	displayYAMLReturns struct {
		result1 error
	}
	displayYAMLReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUI) DisplayTable(arg1 [][]string) {
	var arg1Copy [][]string
	if arg1 != nil {
		arg1Copy = make([][]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.displayTableMutex.Lock()
	fake.displayTableArgsForCall = append(fake.displayTableArgsForCall, struct {
		arg1 [][]string
	}{arg1Copy})
	fake.recordInvocation("DisplayTable", []interface{}{arg1Copy})
	fake.displayTableMutex.Unlock()
	if fake.DisplayTableStub != nil {
		fake.DisplayTableStub(arg1)
	}
}

func (fake *FakeUI) DisplayTableCallCount() int {
	fake.displayTableMutex.RLock()
	defer fake.displayTableMutex.RUnlock()
	return len(fake.displayTableArgsForCall)
}

func (fake *FakeUI) DisplayTableCalls(stub func([][]string)) {
	fake.displayTableMutex.Lock()
	defer fake.displayTableMutex.Unlock()
	fake.DisplayTableStub = stub
}

func (fake *FakeUI) DisplayTableArgsForCall(i int) [][]string {
	fake.displayTableMutex.RLock()
	defer fake.displayTableMutex.RUnlock()
	argsForCall := fake.displayTableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeUI) DisplayText(arg1 string, arg2 ...map[string]interface{}) {
	fake.displayTextMutex.Lock()
	fake.displayTextArgsForCall = append(fake.displayTextArgsForCall, struct {
		arg1 string
		arg2 []map[string]interface{}
	}{arg1, arg2})
	fake.recordInvocation("DisplayText", []interface{}{arg1, arg2})
	fake.displayTextMutex.Unlock()
	if fake.DisplayTextStub != nil {
		fake.DisplayTextStub(arg1, arg2...)
	}
}

func (fake *FakeUI) DisplayTextCallCount() int {
	fake.displayTextMutex.RLock()
	defer fake.displayTextMutex.RUnlock()
	return len(fake.displayTextArgsForCall)
}

func (fake *FakeUI) DisplayTextCalls(stub func(string, ...map[string]interface{})) {
	fake.displayTextMutex.Lock()
	defer fake.displayTextMutex.Unlock()
	fake.DisplayTextStub = stub
}

func (fake *FakeUI) DisplayTextArgsForCall(i int) (string, []map[string]interface{}) {
	fake.displayTextMutex.RLock()
	defer fake.displayTextMutex.RUnlock()
	argsForCall := fake.displayTextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUI) DisplayYAML(arg1 interface{}) error {
	fake.displayYAMLMutex.Lock()
	ret, specificReturn := fake.displayYAMLReturnsOnCall[len(fake.displayYAMLArgsForCall)]
	fake.displayYAMLArgsForCall = append(fake.displayYAMLArgsForCall, struct {
		arg1 interface{}
	}{arg1})
	fake.recordInvocation("DisplayYAML", []interface{}{arg1})
	fake.displayYAMLMutex.Unlock()
	if fake.DisplayYAMLStub != nil {
		return fake.DisplayYAMLStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.displayYAMLReturns
	return fakeReturns.result1
}

func (fake *FakeUI) DisplayYAMLCallCount() int {
	fake.displayYAMLMutex.RLock()
	defer fake.displayYAMLMutex.RUnlock()
	return len(fake.displayYAMLArgsForCall)
}

func (fake *FakeUI) DisplayYAMLCalls(stub func(interface{}) error) {
	fake.displayYAMLMutex.Lock()
	defer fake.displayYAMLMutex.Unlock()
	fake.DisplayYAMLStub = stub
}

func (fake *FakeUI) DisplayYAMLArgsForCall(i int) interface{} {
	fake.displayYAMLMutex.RLock()
	defer fake.displayYAMLMutex.RUnlock()
	argsForCall := fake.displayYAMLArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeUI) DisplayYAMLReturns(result1 error) {
	fake.displayYAMLMutex.Lock()
	defer fake.displayYAMLMutex.Unlock()
	fake.DisplayYAMLStub = nil
	fake.displayYAMLReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUI) DisplayYAMLReturnsOnCall(i int, result1 error) {
	fake.displayYAMLMutex.Lock()
	defer fake.displayYAMLMutex.Unlock()
	fake.DisplayYAMLStub = nil
	if fake.displayYAMLReturnsOnCall == nil {
		fake.displayYAMLReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.displayYAMLReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.displayTableMutex.RLock()
	defer fake.displayTableMutex.RUnlock()
	fake.displayTextMutex.RLock()
	defer fake.displayTextMutex.RUnlock()
	fake.displayYAMLMutex.RLock()
	defer fake.displayYAMLMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commands.UI = new(FakeUI)
