// Code generated by counterfeiter. DO NOT EDIT.
package commandsfakes

import (
	"sync"

	"github.com/pivotal-cf/ism/commands"
	"github.com/pivotal-cf/ism/usecases"
)

type FakeBindingGetUsecase struct {
	GetBindingDetailsByNameStub        func(string) (*usecases.BindingDetails, error)
	getBindingDetailsByNameMutex       sync.RWMutex
	getBindingDetailsByNameArgsForCall []struct {
		arg1 string
	}
	getBindingDetailsByNameReturns struct {
		result1 *usecases.BindingDetails
		result2 error
	}
	getBindingDetailsByNameReturnsOnCall map[int]struct {
		result1 *usecases.BindingDetails
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBindingGetUsecase) GetBindingDetailsByName(arg1 string) (*usecases.BindingDetails, error) {
	fake.getBindingDetailsByNameMutex.Lock()
	ret, specificReturn := fake.getBindingDetailsByNameReturnsOnCall[len(fake.getBindingDetailsByNameArgsForCall)]
	fake.getBindingDetailsByNameArgsForCall = append(fake.getBindingDetailsByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetBindingDetailsByName", []interface{}{arg1})
	fake.getBindingDetailsByNameMutex.Unlock()
	if fake.GetBindingDetailsByNameStub != nil {
		return fake.GetBindingDetailsByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBindingDetailsByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBindingGetUsecase) GetBindingDetailsByNameCallCount() int {
	fake.getBindingDetailsByNameMutex.RLock()
	defer fake.getBindingDetailsByNameMutex.RUnlock()
	return len(fake.getBindingDetailsByNameArgsForCall)
}

func (fake *FakeBindingGetUsecase) GetBindingDetailsByNameCalls(stub func(string) (*usecases.BindingDetails, error)) {
	fake.getBindingDetailsByNameMutex.Lock()
	defer fake.getBindingDetailsByNameMutex.Unlock()
	fake.GetBindingDetailsByNameStub = stub
}

func (fake *FakeBindingGetUsecase) GetBindingDetailsByNameArgsForCall(i int) string {
	fake.getBindingDetailsByNameMutex.RLock()
	defer fake.getBindingDetailsByNameMutex.RUnlock()
	argsForCall := fake.getBindingDetailsByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBindingGetUsecase) GetBindingDetailsByNameReturns(result1 *usecases.BindingDetails, result2 error) {
	fake.getBindingDetailsByNameMutex.Lock()
	defer fake.getBindingDetailsByNameMutex.Unlock()
	fake.GetBindingDetailsByNameStub = nil
	fake.getBindingDetailsByNameReturns = struct {
		result1 *usecases.BindingDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingGetUsecase) GetBindingDetailsByNameReturnsOnCall(i int, result1 *usecases.BindingDetails, result2 error) {
	fake.getBindingDetailsByNameMutex.Lock()
	defer fake.getBindingDetailsByNameMutex.Unlock()
	fake.GetBindingDetailsByNameStub = nil
	if fake.getBindingDetailsByNameReturnsOnCall == nil {
		fake.getBindingDetailsByNameReturnsOnCall = make(map[int]struct {
			result1 *usecases.BindingDetails
			result2 error
		})
	}
	fake.getBindingDetailsByNameReturnsOnCall[i] = struct {
		result1 *usecases.BindingDetails
		result2 error
	}{result1, result2}
}

func (fake *FakeBindingGetUsecase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getBindingDetailsByNameMutex.RLock()
	defer fake.getBindingDetailsByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBindingGetUsecase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commands.BindingGetUsecase = new(FakeBindingGetUsecase)
